### ISSUE TITLE
`CLIc` build results are not cached

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKCLEsperanto#28]
## Overview

The `CLIc` target rebuilds every time a consuming project is built regardless of whether there have been changes in `CLIc` sources. This is a nonblocking issue but does add about a minute to every build iteration.

Initially logging here but may need to be addressed in the CLEsperanto dependency.

## Tested On
Windows 10
Visual Studio 2022
CMake 3.22.3

**Comment by StRigaud** [comment]
I believe this is due to some `add_custom_target` in `CLIc` build configuration.

I use those to run python script in charge of converting ocl kernel files into c++ header files. Although, as they are always (re)generated at each build, this trigger a full project build.

I think I managed to fix this for the next update (hopefully)
- https://github.com/clEsperanto/CLIc_prototype/pull/94/commits/f24f1b2e60e6875223a533f76e80220391c0b273

Thanks for raising this issue!

**Comment by thewtex** [comment]
@StRigaud @tbirdso thanks for working on this!

Does this behavior still exist after we have bumped the `CLIc_prototype` version to the HEAD of `development`?

**Comment by tbirdso** [comment]
I no longer see this behavior in the most recent ITKCLEsperanto build. Thank you for addressing this @StRigaud !
